FROM python:3.11-alpine

RUN apk add --no-cache bash gcc musl-dev libffi-dev
RUN apk add curl proot --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community

WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p shared containers 

EXPOSE 8001

ENV PYTHONUNBUFFERED=1

CMD ["python3", "-m", "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001"]
